basePath: /
definitions:
  models.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.SignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
      passwordConfirm:
        type: string
      photo:
        type: string
    required:
    - email
    - name
    - password
    - passwordConfirm
    - photo
    type: object
host: localhost:8000
info:
  contact: {}
  description: Backend
  title: API
  version: "1.0"
paths:
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out the user by clearing the cookies
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log out the current user
      tags:
      - auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Refreshes the access token when the refresh token is valid
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success, access_token: new_token'
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 'status: fail, message: Invalid or expired refresh token'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh the access token using the refresh token
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Logs in an existing user and generates tokens
      parameters:
      - description: SignIn Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success, access_token: token'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'status: fail, message: Invalid email or Password'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User sign in
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account
      parameters:
      - description: SignUp Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: 'status: success, data: {user: models.UserResponse}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'status: fail, message: Passwords do not match'
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: 'status: fail, message: User with that email already exists'
          schema:
            additionalProperties:
              type: string
            type: object
        "502":
          description: 'status: error, message: Something bad happened'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User sign up
      tags:
      - auth
  /user/me:
    get:
      consumes:
      - application/json
      description: Get the details of the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success, data: {user: models.UserResponse}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'status: fail, message: Bad request'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 'status: fail, message: Unauthorized'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get current authenticated user
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
