version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: social-media-api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: social-media-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: social-media-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  pgdata:
