services:
  db:
    build:
      context: ./postgres
    container_name: social-media-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    container_name: social-media-api
    ports:
      - "8080:8080"
    env_file:
      - ./api/app.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: social-media-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PRIVATE_SWC_USE_WASM=true
    depends_on:
      - api

volumes:
  pgdata:
